apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-operator
  namespace: medcontracthub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-operator
  namespace: medcontracthub
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-operator
  namespace: medcontracthub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backup-operator
subjects:
- kind: ServiceAccount
  name: backup-operator
  namespace: medcontracthub