apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster-config
  namespace: medcontracthub
data:
  redis.conf: |
    port 6379
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    appendfilename "appendonly.aof"
    dir /data
    protected-mode no
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: medcontracthub
  labels:
    app: redis-cluster
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: gossip
  clusterIP: None
  selector:
    app: redis-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-lb
  namespace: medcontracthub
  labels:
    app: redis-cluster
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30379
    name: client
  selector:
    app: redis-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: medcontracthub
spec:
  serviceName: redis-cluster
  replicas: 6
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - redis-cluster
              topologyKey: kubernetes.io/hostname
      containers:
      - name: redis
        image: redis:7-alpine
        command: ["redis-server"]
        args: ["/conf/redis.conf"]
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: gossip
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: conf
          mountPath: /conf
        - name: data
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli ping"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli ping"
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: conf
        configMap:
          name: redis-cluster-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-init
  namespace: medcontracthub
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-redis
        image: busybox:1.35
        command: ['sh', '-c', 'for i in $(seq 0 5); do until nc -z redis-cluster-$i.redis-cluster.medcontracthub.svc.cluster.local 6379; do echo waiting for redis-cluster-$i; sleep 2; done; done']
      containers:
      - name: redis-cluster-init
        image: redis:7-alpine
        command:
        - sh
        - -c
        - |
          # Wait for all Redis nodes to be ready
          sleep 10
          
          # Get pod IPs
          REDIS_NODES=""
          for i in $(seq 0 5); do
            IP=$(getent hosts redis-cluster-$i.redis-cluster.medcontracthub.svc.cluster.local | awk '{ print $1 }')
            REDIS_NODES="$REDIS_NODES $IP:6379"
          done
          
          echo "Creating cluster with nodes: $REDIS_NODES"
          
          # Create the cluster
          echo "yes" | redis-cli --cluster create $REDIS_NODES --cluster-replicas 1
          
          # Check cluster status
          redis-cli --cluster check redis-cluster-0.redis-cluster.medcontracthub.svc.cluster.local:6379