apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: ai-service-ingress
  namespace: medcontracthub
proxy:
  connect_timeout: 30000
  retries: 2
  read_timeout: 120000  # 2 minutes for AI processing
  write_timeout: 120000
upstream:
  healthchecks:
    active:
      healthy:
        http_statuses:
        - 200
        interval: 30
        successes: 2
      http_path: "/health"
      timeout: 10
      unhealthy:
        http_failures: 3
        http_statuses:
        - 500
        - 503
        interval: 30
        tcp_failures: 3
        timeouts: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service-kong
  namespace: medcontracthub
  labels:
    app: ai-service
  annotations:
    konghq.com/plugins: cors-global,jwt-auth,rate-limiting-global,request-transformer-global
    konghq.com/override: ai-service-ingress
spec:
  type: ClusterIP
  ports:
  - port: 8200
    targetPort: 8200
    protocol: TCP
    name: http
  - port: 8201
    targetPort: 8201
    protocol: TCP
    name: grpc
  selector:
    app: ai-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-service-routes
  namespace: medcontracthub
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "true"
    konghq.com/protocols: "http,https"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /api/v1/ai
        pathType: Prefix
        backend:
          service:
            name: ai-service-kong
            port:
              number: 8200
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ai-rate-limit
  namespace: medcontracthub
plugin: rate-limiting
config:
  minute: 60      # Limit AI calls to prevent cost overruns
  hour: 500
  day: 2000
  policy: local
  fault_tolerant: true
  hide_client_headers: false
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ai-request-transformer
  namespace: medcontracthub
plugin: request-transformer
config:
  add:
    headers:
    - "X-AI-Request-ID:$(request_id)"
    - "X-AI-Timestamp:$(timestamp_ms)"
  remove:
    headers:
    - "X-Internal-Model-Key"