apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: analytics-service-ingress
  namespace: medcontracthub
proxy:
  connect_timeout: 10000
  retries: 3
  read_timeout: 60000
  write_timeout: 60000
upstream:
  healthchecks:
    active:
      healthy:
        http_statuses:
        - 200
        interval: 20
        successes: 2
      http_path: "/health"
      timeout: 5
      unhealthy:
        http_failures: 3
        http_statuses:
        - 500
        - 503
        interval: 20
        tcp_failures: 3
        timeouts: 3
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service-kong
  namespace: medcontracthub
  labels:
    app: analytics-service
  annotations:
    konghq.com/plugins: cors-global,jwt-auth,rate-limiting-global
    konghq.com/override: analytics-service-ingress
spec:
  type: ClusterIP
  ports:
  - port: 8300
    targetPort: 8300
    protocol: TCP
    name: http
  selector:
    app: analytics-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: analytics-service-routes
  namespace: medcontracthub
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /api/v1/analytics
        pathType: Prefix
        backend:
          service:
            name: analytics-service-kong
            port:
              number: 8300
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: analytics-cache
  namespace: medcontracthub
plugin: proxy-cache
config:
  response_code:
  - 200
  request_method:
  - GET
  content_type:
  - "application/json"
  cache_ttl: 300  # Cache analytics for 5 minutes
  strategy: memory