apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: main-app-ingress
  namespace: medcontracthub
proxy:
  connect_timeout: 10000
  retries: 3
  read_timeout: 60000
  write_timeout: 60000
upstream:
  healthchecks:
    active:
      healthy:
        http_statuses:
        - 200
        - 302
        interval: 10
        successes: 3
      http_path: "/api/health"
      timeout: 5
      unhealthy:
        http_failures: 5
        http_statuses:
        - 500
        - 503
        interval: 10
        tcp_failures: 5
        timeouts: 5
    passive:
      healthy:
        http_statuses:
        - 200
        - 201
        - 202
        - 204
        successes: 5
      unhealthy:
        http_failures: 5
        http_statuses:
        - 500
        - 503
        tcp_failures: 5
        timeouts: 5
---
apiVersion: v1
kind: Service
metadata:
  name: main-app-kong
  namespace: medcontracthub
  labels:
    app: medcontracthub-app
  annotations:
    konghq.com/plugins: cors-global,rate-limiting-global,request-transformer-global,response-transformer-security
    konghq.com/override: main-app-ingress
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: medcontracthub-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-app-routes
  namespace: medcontracthub
  annotations:
    konghq.com/strip-path: "false"
    konghq.com/preserve-host: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      # API routes
      - path: /api/opportunities
        pathType: Prefix
        backend:
          service:
            name: main-app-kong
            port:
              number: 3000
      - path: /api/proposals
        pathType: Prefix
        backend:
          service:
            name: main-app-kong
            port:
              number: 3000
      - path: /api/compliance
        pathType: Prefix
        backend:
          service:
            name: main-app-kong
            port:
              number: 3000
      - path: /api/billing
        pathType: Prefix
        backend:
          service:
            name: main-app-kong
            port:
              number: 3000
      - path: /api/health
        pathType: Exact
        backend:
          service:
            name: main-app-kong
            port:
              number: 3000
      # Frontend routes
      - path: /
        pathType: Prefix
        backend:
          service:
            name: main-app-kong
            port:
              number: 3000