apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: ocr-service-ingress
  namespace: medcontracthub
proxy:
  connect_timeout: 30000
  retries: 2
  read_timeout: 300000  # 5 minutes for OCR processing
  write_timeout: 300000
upstream:
  healthchecks:
    active:
      healthy:
        http_statuses:
        - 200
        interval: 30
        successes: 2
      http_path: "/health"
      timeout: 10
      unhealthy:
        http_failures: 3
        http_statuses:
        - 500
        - 503
        interval: 30
        tcp_failures: 3
        timeouts: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-service-kong
  namespace: medcontracthub
  labels:
    app: ocr-service
  annotations:
    konghq.com/plugins: cors-global,jwt-auth,request-size-limiting,rate-limiting-global
    konghq.com/override: ocr-service-ingress
spec:
  type: ClusterIP
  ports:
  - port: 8100
    targetPort: 8100
    protocol: TCP
    name: http
  selector:
    app: ocr-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ocr-service-routes
  namespace: medcontracthub
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/methods: "POST,GET"
    konghq.com/preserve-host: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /api/v1/ocr
        pathType: Prefix
        backend:
          service:
            name: ocr-service-kong
            port:
              number: 8100
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ocr-rate-limit
  namespace: medcontracthub
plugin: rate-limiting
config:
  minute: 100
  hour: 1000
  day: 5000
  policy: local
  fault_tolerant: true
  hide_client_headers: false