apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: worker-service-ingress
  namespace: medcontracthub
proxy:
  connect_timeout: 10000
  retries: 3
  read_timeout: 60000
  write_timeout: 60000
upstream:
  healthchecks:
    active:
      healthy:
        http_statuses:
        - 200
        interval: 30
        successes: 2
      http_path: "/health"
      timeout: 5
      unhealthy:
        http_failures: 3
        http_statuses:
        - 500
        - 503
        interval: 30
        tcp_failures: 3
        timeouts: 3
---
apiVersion: v1
kind: Service
metadata:
  name: worker-service-kong
  namespace: medcontracthub
  labels:
    app: worker-service
  annotations:
    konghq.com/plugins: jwt-auth,ip-restriction,rate-limiting-global
    konghq.com/override: worker-service-ingress
spec:
  type: ClusterIP
  ports:
  - port: 8500
    targetPort: 8500
    protocol: TCP
    name: http
  selector:
    app: worker-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worker-service-routes
  namespace: medcontracthub
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      # Admin endpoints (Bull Board UI)
      - path: /admin/queues
        pathType: Prefix
        backend:
          service:
            name: worker-service-kong
            port:
              number: 8500
      # API endpoints for job management
      - path: /api/v1/jobs
        pathType: Prefix
        backend:
          service:
            name: worker-service-kong
            port:
              number: 8500
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: worker-admin-auth
  namespace: medcontracthub
plugin: basic-auth
config:
  hide_credentials: true
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: worker-ip-restriction
  namespace: medcontracthub
plugin: ip-restriction
config:
  allow:
  - 10.0.0.0/8      # Internal k8s network
  - 172.16.0.0/12   # Docker network
  - 192.168.0.0/16  # Local network
  deny: null
  status: 403
  message: "Admin access restricted"