apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medcontracthub

resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - pvc.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml
  - istio-virtualservice.yaml

commonLabels:
  app.kubernetes.io/name: ai-service
  app.kubernetes.io/component: ml
  app.kubernetes.io/part-of: medcontracthub

images:
  - name: medcontracthub/ai-service
    newTag: 1.0.0

replicas:
  - name: ai-service
    count: 2