apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-service-model-cache
  namespace: medcontracthub
  labels:
    app: ai-service
    component: microservice
    tier: ml
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 100Gi