apiVersion: v1
kind: Secret
metadata:
  name: ai-service-secrets
  namespace: medcontracthub
  labels:
    app: ai-service
    component: microservice
    tier: ml
type: Opaque
stringData:
  # API Keys for ML models (will be populated from environment)
  anthropic-api-key: "${ANTHROPIC_API_KEY}"
  openai-api-key: "${OPENAI_API_KEY}"
  mistral-api-key: "${MISTRAL_API_KEY}"
  huggingface-api-key: "${HUGGINGFACE_API_KEY}"
  
  # Database credentials
  postgres-password: "${POSTGRES_PASSWORD}"
  
  # Redis password if configured
  redis-password: "${REDIS_PASSWORD}"