apiVersion: v1
kind: Secret
metadata:
  name: ai-service-secrets
  namespace: medcontracthub
  labels:
    app: ai-service
    component: microservice
    tier: ml
type: Opaque
stringData:
  # API Keys for ML models (will be populated from environment)
  anthropic-api-key: "${ANTHROPIC_API_KEY}"
  openai-api-key: "${OPENAI_API_KEY}"
  mistral-api-key: "${MISTRAL_API_KEY}"
  huggingface-api-key: "${HUGGINGFACE_API_KEY}"
  
  # Weaviate authentication (PostgreSQL removed)
  weaviate-api-key: "${WEAVIATE_API_KEY}"
  weaviate-oidc-client-secret: "${WEAVIATE_OIDC_CLIENT_SECRET}"
  
  # Redis password if configured
  redis-password: "${REDIS_PASSWORD}"
  
  # Additional API keys for embeddings
  cohere-api-key: "${COHERE_API_KEY}"
  voyage-api-key: "${VOYAGE_API_KEY}"