apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-service-config
  namespace: medcontracthub
  labels:
    app: worker-service
    component: microservice
    tier: backend
data:
  environment: "production"
  log_level: "info"
  
  # Redis configuration
  redis_url: "redis://redis-cluster.medcontracthub.svc.cluster.local:6379"
  
  # Kafka configuration
  kafka_brokers: "kafka-0.kafka-headless.medcontracthub.svc.cluster.local:9092,kafka-1.kafka-headless.medcontracthub.svc.cluster.local:9092,kafka-2.kafka-headless.medcontracthub.svc.cluster.local:9092"
  
  # Database configuration
  supabase_url: "${SUPABASE_URL}"
  
  # Email configuration
  email_provider: "sendgrid"
  email_from: "noreply@medcontracthub.com"
  
  # SAM.gov configuration
  sam_gov_base_url: "https://api.sam.gov"
  sam_sync_interval: "360"  # 6 hours in minutes
  
  # Queue configurations
  queue_config:  < /dev/null | 
    {
      "email": {
        "concurrency": 5,
        "defaultJobOptions": {
          "attempts": 3,
          "backoff": {
            "type": "exponential",
            "delay": 5000
          },
          "removeOnComplete": true,
          "removeOnFail": false
        }
      },
      "document": {
        "concurrency": 3,
        "defaultJobOptions": {
          "attempts": 3,
          "timeout": 300000,
          "backoff": {
            "type": "exponential",
            "delay": 10000
          }
        }
      },
      "sync": {
        "concurrency": 1,
        "defaultJobOptions": {
          "attempts": 3,
          "timeout": 600000
        }
      },
      "report": {
        "concurrency": 2,
        "defaultJobOptions": {
          "attempts": 2,
          "timeout": 180000
        }
      }
    }
  
  # Scheduled jobs configuration
  scheduled_jobs: |
    {
      "emailReminders": {
        "enabled": true,
        "cron": "0 9 * * *"
      },
      "samGovSync": {
        "enabled": true,
        "cron": "0 */6 * * *"
      },
      "dataCleanup": {
        "enabled": true,
        "cron": "0 2 * * *",
        "retentionDays": 90
      },
      "reportGeneration": {
        "enabled": true,
        "cron": "0 8 * * MON"
      }
    }
