apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  namespace: medcontracthub
  labels:
    app: worker-service
    version: v1
    component: microservice
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-service
      version: v1
  template:
    metadata:
      labels:
        app: worker-service
        version: v1
        component: microservice
        tier: backend
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8500"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: worker-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: worker-service
        image: medcontracthub/worker-service:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8500
          name: http
          protocol: TCP
        env:
        - name: SERVICE_NAME
          value: "worker-service"
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: worker-service-config
              key: environment
        - name: PORT
          value: "8500"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: worker-service-config
              key: log_level
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: worker-service-config
              key: redis_url
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: worker-service-secrets
              key: redis-password
              optional: true
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: worker-service-config
              key: kafka_brokers
        - name: KAFKA_CLIENT_ID
          value: "worker-service"
        - name: KAFKA_GROUP_ID
          value: "worker-service-group"
        - name: SUPABASE_URL
          valueFrom:
            configMapKeyRef:
              name: worker-service-config
              key: supabase_url
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: worker-service-secrets
              key: supabase-service-role-key
        - name: EMAIL_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: worker-service-config
              key: email_provider
        - name: EMAIL_FROM
          valueFrom:
            configMapKeyRef:
              name: worker-service-config
              key: email_from
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: worker-service-secrets
              key: sendgrid-api-key
              optional: true
        - name: SAM_GOV_API_KEY
          valueFrom:
            secretKeyRef:
              name: worker-service-secrets
              key: sam-gov-api-key
              optional: true
        - name: SAM_GOV_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: worker-service-config
              key: sam_gov_base_url
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: worker-service-secrets
              key: sentry-dsn
              optional: true
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: JAEGER_AGENT_PORT
          value: "6831"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: temp-storage
          mountPath: /tmp
      volumes:
      - name: temp-storage
        emptyDir:
          sizeLimit: 5Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - worker-service
              topologyKey: kubernetes.io/hostname