apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-service
  namespace: medcontracthub
  labels:
    app: worker-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: worker-service
  namespace: medcontracthub
  labels:
    app: worker-service
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worker-service
  namespace: medcontracthub
  labels:
    app: worker-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: worker-service
subjects:
- kind: ServiceAccount
  name: worker-service
  namespace: medcontracthub