apiVersion: v1
kind: Secret
metadata:
  name: worker-service-secrets
  namespace: medcontracthub
  labels:
    app: worker-service
    component: microservice
    tier: backend
type: Opaque
stringData:
  # Database credentials
  postgres-password: "${POSTGRES_PASSWORD}"
  
  # Redis password if configured
  redis-password: "${REDIS_PASSWORD}"
  
  # AWS credentials for S3
  aws-access-key-id: "${AWS_ACCESS_KEY_ID}"
  aws-secret-access-key: "${AWS_SECRET_ACCESS_KEY}"
  
  # Email service credentials
  email-from: "${EMAIL_FROM}"
  resend-api-key: "${RESEND_API_KEY}"
  
  # External API keys
  mistral-api-key: "${MISTRAL_API_KEY}"
  sam-gov-api-key: "${SAM_GOV_API_KEY}"