apiVersion: v1
kind: Secret
metadata:
  name: worker-service-secrets
  namespace: medcontracthub
  labels:
    app: worker-service
    component: microservice
    tier: backend
type: Opaque
stringData:
  # Redis password (if configured)
  redis-password: "${REDIS_PASSWORD}"
  
  # Supabase service role key
  supabase-service-role-key: "${SUPABASE_SERVICE_ROLE_KEY}"
  
  # Email provider keys
  sendgrid-api-key: "${SENDGRID_API_KEY}"
  smtp-password: "${SMTP_PASSWORD}"
  
  # SAM.gov API key
  sam-gov-api-key: "${SAM_GOV_API_KEY}"
  
  # Monitoring
  sentry-dsn: "${SENTRY_DSN}"
EOF < /dev/null
