apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: medcontracthub
  labels:
    app: worker-service
    component: microservice
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: worker-service
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics