apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: medcontracthub
  labels:
    app: worker-service
    component: microservice
    tier: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8500"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: worker-service
  ports:
  - name: http
    port: 8500
    targetPort: http
    protocol: TCP
  sessionAffinity: None