apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocr-service
  namespace: medcontracthub
  labels:
    app: ocr-service
    component: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ocr-service-role
  namespace: medcontracthub
  labels:
    app: ocr-service
    component: rbac
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ocr-service-rolebinding
  namespace: medcontracthub
  labels:
    app: ocr-service
    component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ocr-service-role
subjects:
- kind: ServiceAccount
  name: ocr-service
  namespace: medcontracthub