apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ocr-service-monitor
  namespace: medcontracthub
  labels:
    app: ocr-service
    component: monitoring
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: ocr-service
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    metricRelabelings:
    - regex: '(ocr_requests_total|ocr_processing_seconds|ocr_cache_hits_total)'
      sourceLabels: [__name__]
      action: keep