// This file will be auto-generated by running: npm run db:types
// For now, we'll create a placeholder type

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          company_id: string | null
          email: string
          full_name: string | null
          phone: string | null
          title: string | null
          role: 'admin' | 'user'
          avatar_url: string | null
          is_active: boolean
          onboarding_completed: boolean
          email_notifications: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      companies: {
        Row: {
          id: string
          name: string
          duns_number: string | null
          cage_code: string | null
          ein: string | null
          description: string | null
          address_line1: string | null
          address_line2: string | null
          city: string | null
          state: string | null
          zip_code: string | null
          phone: string | null
          website: string | null
          certifications: string[]
          naics_codes: string[]
          sam_registration_date: string | null
          sam_expiration_date: string | null
          subscription_plan: 'starter' | 'pro' | 'enterprise'
          subscription_status: string
          stripe_customer_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['companies']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['companies']['Insert']>
      }
      // Add other tables as needed
    }
    Views: {}
    Functions: {}
    Enums: {}
    CompositeTypes: {}
  }
}