// This file will be auto-generated by running: npm run db:types
// For now, we'll create a placeholder type

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          company_id: string | null
          email: string
          full_name: string | null
          phone: string | null
          title: string | null
          role: 'admin' | 'user'
          avatar_url: string | null
          is_active: boolean
          onboarding_completed: boolean
          email_notifications: boolean
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      companies: {
        Row: {
          id: string
          name: string
          duns_number: string | null
          cage_code: string | null
          ein: string | null
          description: string | null
          address_line1: string | null
          address_line2: string | null
          city: string | null
          state: string | null
          zip_code: string | null
          phone: string | null
          website: string | null
          certifications: string[]
          naics_codes: string[]
          sam_registration_date: string | null
          sam_expiration_date: string | null
          subscription_plan: 'starter' | 'pro' | 'enterprise'
          subscription_status: string
          stripe_customer_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['companies']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['companies']['Insert']>
      }
      opportunities: {
        Row: {
          id: string
          notice_id: string
          title: string
          description: string | null
          agency: string
          sub_agency: string | null
          office: string | null
          posted_date: string
          response_deadline: string
          archive_date: string | null
          naics_code: string | null
          naics_description: string | null
          place_of_performance_state: string | null
          place_of_performance_city: string | null
          set_aside_type: string | null
          contract_type: string | null
          estimated_value_min: number | null
          estimated_value_max: number | null
          award_date: string | null
          award_amount: number | null
          awardee_name: string | null
          awardee_duns: string | null
          status: 'active' | 'awarded' | 'cancelled' | 'expired'
          solicitation_number: string | null
          primary_contact_name: string | null
          primary_contact_email: string | null
          primary_contact_phone: string | null
          attachments: any[]
          additional_info: any
          sam_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['opportunities']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['opportunities']['Insert']>
      }
      saved_opportunities: {
        Row: {
          id: string
          user_id: string
          opportunity_id: string
          notes: string | null
          tags: string[]
          is_pursuing: boolean
          reminder_date: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['saved_opportunities']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['saved_opportunities']['Insert']>
      }
    }
    Views: {}
    Functions: {}
    Enums: {}
    CompositeTypes: {}
  }
}