apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: analytics-service-pdb
  namespace: medcontracthub
  labels:
    app: analytics-service
    component: microservice
    tier: analytics
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: analytics-service