apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  namespace: medcontracthub
  labels:
    app: analytics-service
    component: microservice
    tier: analytics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: analytics-service-role
  namespace: medcontracthub
  labels:
    app: analytics-service
    component: microservice
    tier: analytics
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "create", "update", "patch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: analytics-service-rolebinding
  namespace: medcontracthub
  labels:
    app: analytics-service
    component: microservice
    tier: analytics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: analytics-service-role
subjects:
- kind: ServiceAccount
  name: analytics-service
  namespace: medcontracthub