apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secrets
  namespace: medcontracthub
  labels:
    app: analytics-service
    component: microservice
    tier: analytics
type: Opaque
stringData:
  # Database credentials
  postgres-password: "${POSTGRES_PASSWORD}"
  clickhouse-password: "${CLICKHOUSE_PASSWORD}"
  
  # Redis password if configured
  redis-password: "${REDIS_PASSWORD}"
  
  # API keys for external analytics services
  segment-write-key: "${SEGMENT_WRITE_KEY}"
  mixpanel-api-key: "${MIXPANEL_API_KEY}"