apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: medcontracthub
  labels:
    app: analytics-service
    component: microservice
    tier: analytics
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
  - port: 8300
    targetPort: 8300
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics