apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: devops@medcontracthub.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: devops@medcontracthub.com
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
# Wildcard certificate for *.medcontracthub.com
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: medcontracthub-wildcard
  namespace: medcontracthub
spec:
  secretName: medcontracthub-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: '*.medcontracthub.com'
  dnsNames:
  - medcontracthub.com
  - '*.medcontracthub.com'
  - '*.api.medcontracthub.com'
  - '*.app.medcontracthub.com'