apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-replica
  namespace: medcontracthub
  labels:
    app: postgres
    component: database
    tier: data
    role: replica
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-replica-role
  namespace: medcontracthub
  labels:
    app: postgres
    component: database
    tier: data
    role: replica
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-replica-rolebinding
  namespace: medcontracthub
  labels:
    app: postgres
    component: database
    tier: data
    role: replica
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-replica-role
subjects:
- kind: ServiceAccount
  name: postgres-replica
  namespace: medcontracthub