apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-primary
  namespace: medcontracthub
  labels:
    app: postgres-primary
    component: database
    tier: data
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-primary-role
  namespace: medcontracthub
  labels:
    app: postgres-primary
    component: database
    tier: data
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-primary-rolebinding
  namespace: medcontracthub
  labels:
    app: postgres-primary
    component: database
    tier: data
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-primary-role
subjects:
- kind: ServiceAccount
  name: postgres-primary
  namespace: medcontracthub