apiVersion: v1
kind: Secret
metadata:
  name: postgres-primary-secrets
  namespace: medcontracthub
  labels:
    app: postgres-primary
    component: database
    tier: data
type: Opaque
stringData:
  postgres-password: "${POSTGRES_PASSWORD}"
  replicator-password: "${POSTGRES_REPLICATOR_PASSWORD}"