apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
  namespace: medcontracthub
  labels:
    app: postgres-primary
    component: database
    tier: data
    role: primary
spec:
  type: ClusterIP
  selector:
    app: postgres-primary
    role: primary
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-primary-headless
  namespace: medcontracthub
  labels:
    app: postgres-primary
    component: database
    tier: data
    role: primary
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: postgres-primary
    role: primary
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-read
  namespace: medcontracthub
  labels:
    app: postgres
    component: database
    tier: data
    role: read
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  selector:
    app: postgres
    role: replica
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres