apiVersion: v1
kind: ServiceAccount
metadata:
  name: realtime-service
  namespace: medcontracthub
  labels:
    app: realtime-service
    component: microservice
    tier: realtime
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: realtime-service-role
  namespace: medcontracthub
  labels:
    app: realtime-service
    component: microservice
    tier: realtime
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets/scale"]
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: realtime-service-rolebinding
  namespace: medcontracthub
  labels:
    app: realtime-service
    component: microservice
    tier: realtime
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: realtime-service-role
subjects:
- kind: ServiceAccount
  name: realtime-service
  namespace: medcontracthub