apiVersion: v1
kind: Secret
metadata:
  name: realtime-service-secrets
  namespace: medcontracthub
  labels:
    app: realtime-service
    component: microservice
    tier: realtime
type: Opaque
stringData:
  # Redis password if configured
  redis-password: "${REDIS_PASSWORD}"
  
  # JWT secret for WebSocket authentication
  jwt-secret: "${JWT_SECRET}"
  
  # Encryption key for real-time data
  encryption-key: "${REALTIME_ENCRYPTION_KEY}"