apiVersion: v1
kind: Service
metadata:
  name: realtime-service
  namespace: medcontracthub
  labels:
    app: realtime-service
    component: microservice
    tier: realtime
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: ClusterIP
  selector:
    app: realtime-service
  ports:
  - port: 8400
    targetPort: 8400
    protocol: TCP
    name: websocket
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400  # 24 hours for WebSocket connections
---
apiVersion: v1
kind: Service
metadata:
  name: realtime-service-headless
  namespace: medcontracthub
  labels:
    app: realtime-service
    component: microservice
    tier: realtime
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: realtime-service
  ports:
  - port: 8400
    targetPort: 8400
    protocol: TCP
    name: websocket
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics