# Elasticsearch Helm Values for MedContractHub
clusterName: "medcontracthub-logs"
nodeGroup: "master"

# 3-node cluster for HA
replicas: 3

# Resource configuration
resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi"

# Persistent storage
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
  storageClassName: "fast-ssd"

# Security
xpack:
  security:
    enabled: true
    transport:
      ssl:
        enabled: true
    http:
      ssl:
        enabled: true

# Elasticsearch configuration
esConfig:
  elasticsearch.yml: |
    cluster.name: "medcontracthub-logs"
    network.host: 0.0.0.0
    discovery.type: zen
    discovery.zen.minimum_master_nodes: 2
    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: true
    xpack.ml.enabled: true
    # Index lifecycle management
    xpack.ilm.enabled: true
    # Set retention for different log types
    indices.lifecycle.poll_interval: 10m

# JVM Options
esJavaOpts: "-Xmx2g -Xms2g"

# Anti-affinity for production
antiAffinity: "hard"

# Pod Disruption Budget
maxUnavailable: 1

# Service configuration
service:
  type: ClusterIP
  httpPortName: http
  transportPortName: transport

# Readiness probe
readinessProbe:
  httpGet:
    path: /_cluster/health?local=true
    port: 9200
  initialDelaySeconds: 60
  periodSeconds: 10

# Index templates for MedContractHub
lifecycle:
  enabled: true
  policies:
    medcontracthub-logs:
      phases:
        hot:
          actions:
            rollover:
              max_size: 50GB
              max_age: 7d
        warm:
          min_age: 7d
          actions:
            shrink:
              number_of_shards: 1
            forcemerge:
              max_num_segments: 1
        cold:
          min_age: 30d
          actions:
            freeze: {}
        delete:
          min_age: 90d
          actions:
            delete: {}