apiVersion: v1
kind: ConfigMap
metadata:
  name: medcontracthub-config
  namespace: medcontracthub
data:
  # Application Configuration
  NODE_ENV: "development"
  NEXT_TELEMETRY_DISABLED: "1"
  
  # Redis Configuration
  REDIS_URL: "redis://redis-cluster-lb:6379"
  REDIS_CLUSTER_ENABLED: "true"
  
  # Kafka Configuration
  KAFKA_BROKERS: "kafka-0.kafka.kafka.svc.cluster.local:9092,kafka-1.kafka.kafka.svc.cluster.local:9092,kafka-2.kafka.kafka.svc.cluster.local:9092"
  KAFKA_CLIENT_ID: "medcontracthub-app"
  KAFKA_GROUP_ID: "medcontracthub-group"
  
  # OCR Service Configuration
  OCR_SERVICE_URL: "http://ocr-service:8100"
  OCR_SERVICE_TIMEOUT: "30000"
  
  # Kong API Gateway
  KONG_ADMIN_URL: "http://kong-kong-admin:8001"
  KONG_PROXY_URL: "http://kong-kong-proxy:80"
  
  # Monitoring
  ENABLE_TRACING: "true"
  JAEGER_AGENT_HOST: "jaeger-agent.observability"
  JAEGER_AGENT_PORT: "6831"
  
  # Feature Flags
  ENABLE_MICROSERVICES: "true"
  ENABLE_KAFKA_EVENTS: "true"
  ENABLE_DISTRIBUTED_CACHE: "true"