apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse
  namespace: medcontracthub
  labels:
    app: clickhouse
    component: database
    tier: analytics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clickhouse-role
  namespace: medcontracthub
  labels:
    app: clickhouse
    component: database
    tier: analytics
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clickhouse-rolebinding
  namespace: medcontracthub
  labels:
    app: clickhouse
    component: database
    tier: analytics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: clickhouse-role
subjects:
- kind: ServiceAccount
  name: clickhouse
  namespace: medcontracthub