apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secrets
  namespace: medcontracthub
  labels:
    app: clickhouse
    component: database
    tier: analytics
type: Opaque
stringData:
  default-password: "${CLICKHOUSE_DEFAULT_PASSWORD}"
  analytics-password: "${CLICKHOUSE_ANALYTICS_PASSWORD}"