apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: medcontracthub
  labels:
    app: clickhouse
    component: database
    tier: analytics
spec:
  type: ClusterIP
  selector:
    app: clickhouse
  ports:
  - port: 8123
    targetPort: 8123
    protocol: TCP
    name: http
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-headless
  namespace: medcontracthub
  labels:
    app: clickhouse
    component: database
    tier: analytics
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: clickhouse
  ports:
  - port: 8123
    targetPort: 8123
    protocol: TCP
    name: http
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: tcp
  - port: 9009
    targetPort: 9009
    protocol: TCP
    name: interserver