apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: medcontracthub
  labels:
    app: medcontracthub
    component: ingress
data:
  X-Frame-Options: "DENY"
  X-Content-Type-Options: "nosniff"
  X-XSS-Protection: "1; mode=block"
  Referrer-Policy: "strict-origin-when-cross-origin"
  Permissions-Policy: "camera=(), microphone=(), geolocation=()"
  X-Permitted-Cross-Domain-Policies: "none"
  X-Download-Options: "noopen"