apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: analytics-service-monitor
  namespace: medcontracthub
  labels:
    app: analytics-service
    component: microservice
    tier: analytics
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: analytics-service
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_pod_container_name]
      targetLabel: container
    metricRelabelings:
    # Add service label to all metrics
    - sourceLabels: [__name__]
      targetLabel: service
      replacement: analytics-service