apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-service-monitor
  namespace: medcontracthub
  labels:
    app: worker-service
    component: microservice
    tier: background
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: worker-service
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_pod_container_name]
      targetLabel: container
    metricRelabelings:
    - sourceLabels: [__name__]
      targetLabel: service
      replacement: worker-service