apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: medcontracthub
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: medcontracthub
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/MedContractHubSecretsRole
---
# Example ExternalSecret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: medcontracthub
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: database-credentials
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: medcontracthub/prod/postgres
      property: password
  - secretKey: redis-password
    remoteRef:
      key: medcontracthub/prod/redis
      property: password
  - secretKey: clickhouse-password
    remoteRef:
      key: medcontracthub/prod/clickhouse
      property: password