apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: medcontracthub
spec:
  provider:
    vault:
      server: "https://vault.medcontracthub.com:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "medcontracthub"
          serviceAccountRef:
            name: vault-auth-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth-sa
  namespace: medcontracthub
---
# Example ExternalSecret for Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-service-secrets
  namespace: medcontracthub
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: ai-service-secrets
    creationPolicy: Owner
  data:
  - secretKey: openai-api-key
    remoteRef:
      key: secret/data/medcontracthub/ai-service
      property: openai_api_key
  - secretKey: anthropic-api-key
    remoteRef:
      key: secret/data/medcontracthub/ai-service
      property: anthropic_api_key
  - secretKey: mistral-api-key
    remoteRef:
      key: secret/data/medcontracthub/ai-service
      property: mistral_api_key