apiVersion: v1
kind: ServiceAccount
metadata:
  name: weaviate
  namespace: medcontracthub
  labels:
    app: weaviate
    component: database
    tier: data
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: weaviate-role
  namespace: medcontracthub
  labels:
    app: weaviate
    component: database
    tier: data
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: weaviate-rolebinding
  namespace: medcontracthub
  labels:
    app: weaviate
    component: database
    tier: data
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: weaviate-role
subjects:
- kind: ServiceAccount
  name: weaviate
  namespace: medcontracthub