apiVersion: v1
kind: Secret
metadata:
  name: weaviate-secrets
  namespace: medcontracthub
  labels:
    app: weaviate
    component: database
    tier: data
type: Opaque
stringData:
  openai-api-key: "${OPENAI_API_KEY}"
  huggingface-api-key: "${HUGGINGFACE_API_KEY}"
  oidc-client-secret: "${WEAVIATE_OIDC_CLIENT_SECRET}"