apiVersion: v1
kind: Service
metadata:
  name: weaviate
  namespace: medcontracthub
  labels:
    app: weaviate
    component: database
    tier: data
spec:
  type: ClusterIP
  selector:
    app: weaviate
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 2112
    targetPort: 2112
    protocol: TCP
    name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: weaviate-headless
  namespace: medcontracthub
  labels:
    app: weaviate
    component: database
    tier: data
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: weaviate
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 7946
    targetPort: 7946
    protocol: TCP
    name: gossip
  - port: 7947
    targetPort: 7947
    protocol: TCP
    name: data