apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: weaviate
  namespace: medcontracthub
  labels:
    app: weaviate
    component: database
    tier: data
spec:
  serviceName: weaviate-headless
  replicas: 3
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
        component: database
        tier: data
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2112"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: weaviate
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
      - name: weaviate
        image: semitechnologies/weaviate:1.23.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 2112
          name: metrics
          protocol: TCP
        env:
        - name: WEAVIATE_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: WEAVIATE_SCHEME
          value: "http"
        - name: WEAVIATE_PORT
          value: "8080"
        - name: PROMETHEUS_MONITORING_ENABLED
          value: "true"
        - name: PROMETHEUS_MONITORING_PORT
          value: "2112"
        - name: QUERY_MAXIMUM_RESULTS
          value: "10000"
        - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
          value: "false"
        - name: AUTHENTICATION_OIDC_ENABLED
          value: "true"
        - name: AUTHENTICATION_OIDC_ISSUER
          value: "https://medcontracthub.com/auth"
        - name: AUTHENTICATION_OIDC_CLIENT_ID
          value: "weaviate-client"
        - name: AUTHENTICATION_OIDC_USERNAME_CLAIM
          value: "email"
        - name: AUTHENTICATION_OIDC_GROUPS_CLAIM
          value: "groups"
        - name: AUTHORIZATION_ADMINLIST_ENABLED
          value: "true"
        - name: AUTHORIZATION_ADMINLIST_USERS
          value: "admin@medcontracthub.com"
        - name: PERSISTENCE_DATA_PATH
          value: "/var/lib/weaviate"
        - name: DEFAULT_VECTORIZER_MODULE
          value: "text2vec-openai"
        - name: ENABLE_MODULES
          value: "text2vec-openai,text2vec-huggingface,qna-openai,generative-openai"
        - name: CLUSTER_HOSTNAME
          value: "weaviate"
        - name: CLUSTER_GOSSIP_BIND_PORT
          value: "7946"
        - name: CLUSTER_DATA_BIND_PORT
          value: "7947"
        - name: RAFT_ENABLE
          value: "true"
        - name: RAFT_BOOTSTRAP_EXPECT
          value: "3"
        - name: OPENAI_APIKEY
          valueFrom:
            secretKeyRef:
              name: weaviate-secrets
              key: openai-api-key
        - name: HUGGINGFACE_APIKEY
          valueFrom:
            secretKeyRef:
              name: weaviate-secrets
              key: huggingface-api-key
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        livenessProbe:
          httpGet:
            path: /v1/.well-known/live
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /v1/.well-known/ready
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /var/lib/weaviate
        - name: config
          mountPath: /etc/weaviate
      volumes:
      - name: config
        configMap:
          name: weaviate-config
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: weaviate
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: fast-ssd
      resources:
        requests:
          storage: 100Gi