apiVersion: apps/v1
kind: Deployment
metadata:
  name: medcontracthub-app
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: NODE_ENV
          value: development
        - name: NEXT_PUBLIC_API_URL
          value: http://localhost:31000
        resources:
          limits:
            memory: 1Gi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-service
spec:
  template:
    spec:
      containers:
      - name: ocr-service
        env:
        - name: ENVIRONMENT
          value: development
        - name: LOG_LEVEL
          value: DEBUG
        resources:
          limits:
            memory: 1Gi
            cpu: 500m
          requests:
            memory: 512Mi
            cpu: 200m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-adapter
spec:
  template:
    spec:
      containers:
      - name: adapter
        env:
        - name: NODE_ENV
          value: development
        - name: LOG_LEVEL
          value: debug
        resources:
          limits:
            memory: 512Mi
            cpu: 250m
          requests:
            memory: 128Mi
            cpu: 50m