apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: medcontracthub
  labels:
    app: kong
    component: configuration
data:
  postgres_host: "postgres-kong.medcontracthub.svc.cluster.local"
  postgres_database: "kong"
  nginx_worker_processes: "2"
  log_level: "info"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-declarative-config
  namespace: medcontracthub
  labels:
    app: kong
    component: configuration
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    services:
    # OCR Service
    - name: ocr-service
      url: http://ocr-service.medcontracthub.svc.cluster.local:8100
      protocol: http
      host: ocr-service.medcontracthub.svc.cluster.local
      port: 8100
      path: /
      retries: 5
      connect_timeout: 60000
      write_timeout: 300000
      read_timeout: 300000
      routes:
      - name: ocr-route
        protocols:
        - http
        - https
        paths:
        - /api/v1/ocr
        strip_path: true
        preserve_host: false
      plugins:
      - name: rate-limiting
        config:
          minute: 100
          hour: 1000
          policy: local
      - name: request-size-limiting
        config:
          allowed_payload_size: 50
      - name: cors
        config:
          origins:
          - "*"
          methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
          headers:
          - Accept
          - Accept-Version
          - Content-Length
          - Content-MD5
          - Content-Type
          - Date
          - X-Auth-Token
          - X-Request-ID
          exposed_headers:
          - X-Auth-Token
          - X-Request-ID
          credentials: true
          max_age: 3600
      - name: jwt
        config:
          secret_is_base64: false
          claims_to_verify:
          - exp
      - name: prometheus

    # Main Application
    - name: medcontracthub-app
      url: http://medcontracthub-app.medcontracthub.svc.cluster.local:3000
      protocol: http
      host: medcontracthub-app.medcontracthub.svc.cluster.local
      port: 3000
      path: /
      retries: 3
      connect_timeout: 60000
      write_timeout: 60000
      read_timeout: 60000
      routes:
      - name: app-route
        protocols:
        - http
        - https
        paths:
        - /
        preserve_host: true
      plugins:
      - name: rate-limiting
        config:
          minute: 1000
          hour: 10000
          policy: local
      - name: cors
        config:
          origins:
          - "*"
          methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
          headers:
          - Accept
          - Accept-Version
          - Content-Length
          - Content-MD5
          - Content-Type
          - Date
          - X-Auth-Token
          - X-Request-ID
          exposed_headers:
          - X-Auth-Token
          - X-Request-ID
          credentials: true
          max_age: 3600
      - name: prometheus

    # Health Check Service
    - name: health-check
      url: http://medcontracthub-app.medcontracthub.svc.cluster.local:3000/api/health
      protocol: http
      host: medcontracthub-app.medcontracthub.svc.cluster.local
      port: 3000
      path: /api/health
      routes:
      - name: health-route
        protocols:
        - http
        - https
        paths:
        - /health
        strip_path: true
      plugins:
      - name: response-transformer
        config:
          add:
            headers:
            - "X-Kong-Upstream-Status: healthy"

    plugins:
    # Global plugins
    - name: correlation-id
      config:
        header_name: X-Request-ID
        generator: uuid
        echo_downstream: true
    - name: request-transformer
      config:
        add:
          headers:
          - "X-Forwarded-Prefix: /"
    - name: response-transformer
      config:
        add:
          headers:
          - "X-Content-Type-Options: nosniff"
          - "X-Frame-Options: DENY"
          - "X-XSS-Protection: 1; mode=block"
          - "Strict-Transport-Security: max-age=31536000; includeSubDomains"
    
    upstreams:
    - name: ocr-service-upstream
      algorithm: least-connections
      healthchecks:
        active:
          type: http
          http_path: /health
          healthy:
            interval: 10
            successes: 2
          unhealthy:
            interval: 5
            http_failures: 5
        passive:
          type: http
          healthy:
            successes: 5
          unhealthy:
            http_failures: 5
      targets:
      - target: ocr-service.medcontracthub.svc.cluster.local:8100
        weight: 100