apiVersion: v1
kind: Secret
metadata:
  name: kong-enterprise-license
  namespace: medcontracthub
type: Opaque
stringData:
  license: ""  # Add Kong Enterprise license if using Enterprise features
---
apiVersion: v1
kind: Secret
metadata:
  name: kong-session-conf
  namespace: medcontracthub
type: Opaque
stringData:
  session_secret: "changeme-session-secret-32-chars-long"
  admin_gui_session_conf: '{"cookie_name":"admin_session","secret":"changeme-admin-secret","cookie_secure":true,"storage":"kong"}'
  portal_session_conf: '{"cookie_name":"portal_session","secret":"changeme-portal-secret","cookie_secure":true,"storage":"kong"}'
---
apiVersion: v1
kind: Secret
metadata:
  name: kong-jwt-secrets
  namespace: medcontracthub
type: Opaque
stringData:
  jwt_secret: "changeme-jwt-secret-key"
  jwt_public_key: |
    -----BEGIN PUBLIC KEY-----
    # Add your JWT public key here
    -----END PUBLIC KEY-----
  jwt_private_key: |
    -----BEGIN PRIVATE KEY-----
    # Add your JWT private key here
    -----END PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: kong-oidc-secrets
  namespace: medcontracthub
type: Opaque
stringData:
  client_id: "medcontracthub-api"
  client_secret: "changeme-oidc-client-secret"
  session_secret: "changeme-oidc-session-secret"