apiVersion: v1
kind: Secret
metadata:
  name: kong-postgres-secret
  namespace: medcontracthub
type: Opaque
stringData:
  password: kongpass123!
  postgres-password: postgrespass123!
---
apiVersion: v1
kind: Service
metadata:
  name: kong-postgres
  namespace: medcontracthub
  labels:
    app: postgres
    component: kong-database
spec:
  type: ClusterIP
  selector:
    app: postgres
    component: kong-database
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kong-postgres
  namespace: medcontracthub
  labels:
    app: postgres
    component: kong-database
spec:
  serviceName: kong-postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      component: kong-database
  template:
    metadata:
      labels:
        app: postgres
        component: kong-database
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: kong
        - name: POSTGRES_USER
          value: kong
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgres-secret
              key: password
        - name: POSTGRES_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgres-secret
              key: postgres-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - kong
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - kong
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: fast-ssd
      resources:
        requests:
          storage: 20Gi