apiVersion: v1
kind: ServiceAccount
metadata:
  name: kong
  namespace: medcontracthub
  labels:
    app: kong
    component: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kong-role
  namespace: medcontracthub
  labels:
    app: kong
    component: rbac
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["configuration.konghq.com"]
  resources: ["kongplugins", "kongconsumers", "kongcredentials", "kongingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kong-rolebinding
  namespace: medcontracthub
  labels:
    app: kong
    component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kong-role
subjects:
- kind: ServiceAccount
  name: kong
  namespace: medcontracthub