apiVersion: v1
kind: Secret
metadata:
  name: kong-secrets
  namespace: medcontracthub
  labels:
    app: kong
    component: secrets
type: Opaque
stringData:
  postgres_user: kong
  postgres_password: kongpassword  # Change this in production
  jwt_secret: your-jwt-secret-here  # Change this in production
  session_secret: your-session-secret-here  # Change this in production